name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Trigger a release on tag push
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v4

    # Build for macOS
    - name: Build executable for macOS
      run: make TARGET=myapp-macos
      # Assuming 'make TARGET=myapp-macos' outputs 'myapp-macos' binary

    # Build for Windows
    - name: Build executable for Windows
      run: make TARGET=myapp-windows.exe
      # Assuming 'make TARGET=myapp-windows.exe' outputs 'myapp-windows.exe' binary

    # Create a new release and upload artifacts
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    # Upload macOS executable
    - name: Upload macOS executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./myapp-macos
        asset_name: myapp-macos
        asset_content_type: application/octet-stream

    # Upload Windows executable
    - name: Upload Windows executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./myapp-windows.exe
        asset_name: myapp-windows.exe
        asset_content_type: application/octet-stream
